// Code generated by MockGen. DO NOT EDIT.
// Source: ./commander.go
//
// Generated by this command:
//
//	mockgen -package=executor -source=./commander.go -destination=./commander_mock.go
//
// Package executor is a generated GoMock package.
package executor

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockcommander is a mock of commander interface.
type Mockcommander struct {
	ctrl     *gomock.Controller
	recorder *MockcommanderMockRecorder
}

// MockcommanderMockRecorder is the mock recorder for Mockcommander.
type MockcommanderMockRecorder struct {
	mock *Mockcommander
}

// NewMockcommander creates a new mock instance.
func NewMockcommander(ctrl *gomock.Controller) *Mockcommander {
	mock := &Mockcommander{ctrl: ctrl}
	mock.recorder = &MockcommanderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcommander) EXPECT() *MockcommanderMockRecorder {
	return m.recorder
}

// execGoListAll mocks base method.
func (m *Mockcommander) execGoListAll() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "execGoListAll")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// execGoListAll indicates an expected call of execGoListAll.
func (mr *MockcommanderMockRecorder) execGoListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "execGoListAll", reflect.TypeOf((*Mockcommander)(nil).execGoListAll))
}

// execGoRun mocks base method.
func (m *Mockcommander) execGoRun(targetFile string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "execGoRun", targetFile)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// execGoRun indicates an expected call of execGoRun.
func (mr *MockcommanderMockRecorder) execGoRun(targetFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "execGoRun", reflect.TypeOf((*Mockcommander)(nil).execGoRun), targetFile)
}
