// Code generated by MockGen. DO NOT EDIT.
// Source: ./filer.go
//
// Generated by this command:
//
//	mockgen -package=executor -source=./filer.go -destination=./filer_mock.go
//
// Package executor is a generated GoMock package.
package executor

import (
	ast "go/ast"
	token "go/token"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockfiler is a mock of filer interface.
type Mockfiler struct {
	ctrl     *gomock.Controller
	recorder *MockfilerMockRecorder
}

// MockfilerMockRecorder is the mock recorder for Mockfiler.
type MockfilerMockRecorder struct {
	mock *Mockfiler
}

// NewMockfiler creates a new mock instance.
func NewMockfiler(ctrl *gomock.Controller) *Mockfiler {
	mock := &Mockfiler{ctrl: ctrl}
	mock.recorder = &MockfilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockfiler) EXPECT() *MockfilerMockRecorder {
	return m.recorder
}

// cleanupGoSumFile mocks base method.
func (m *Mockfiler) cleanupGoSumFile(targetDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "cleanupGoSumFile", targetDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// cleanupGoSumFile indicates an expected call of cleanupGoSumFile.
func (mr *MockfilerMockRecorder) cleanupGoSumFile(targetDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "cleanupGoSumFile", reflect.TypeOf((*Mockfiler)(nil).cleanupGoSumFile), targetDir)
}

// createSessionSrcDir mocks base method.
func (m *Mockfiler) createSessionSrcDir() (string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createSessionSrcDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// createSessionSrcDir indicates an expected call of createSessionSrcDir.
func (mr *MockfilerMockRecorder) createSessionSrcDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createSessionSrcDir", reflect.TypeOf((*Mockfiler)(nil).createSessionSrcDir))
}

// createSessionSrcFile mocks base method.
func (m *Mockfiler) createSessionSrcFile() (*os.File, string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createSessionSrcFile")
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(func())
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// createSessionSrcFile indicates an expected call of createSessionSrcFile.
func (mr *MockfilerMockRecorder) createSessionSrcFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createSessionSrcFile", reflect.TypeOf((*Mockfiler)(nil).createSessionSrcFile))
}

// flush mocks base method.
func (m *Mockfiler) flush(ast *ast.File, targetFile *os.File, fset *token.FileSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "flush", ast, targetFile, fset)
	ret0, _ := ret[0].(error)
	return ret0
}

// flush indicates an expected call of flush.
func (mr *MockfilerMockRecorder) flush(ast, targetFile, fset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "flush", reflect.TypeOf((*Mockfiler)(nil).flush), ast, targetFile, fset)
}

// prepareGoModFile mocks base method.
func (m *Mockfiler) prepareGoModFile(targetDir string, content []byte) (string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "prepareGoModFile", targetDir, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// prepareGoModFile indicates an expected call of prepareGoModFile.
func (mr *MockfilerMockRecorder) prepareGoModFile(targetDir, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "prepareGoModFile", reflect.TypeOf((*Mockfiler)(nil).prepareGoModFile), targetDir, content)
}
