// Code generated by MockGen. DO NOT EDIT.
// Source: ./filer.go
//
// Generated by this command:
//
//	mockgen -package=executor -source=./filer.go -destination=./filer_mock.go
//
// Package executor is a generated GoMock package.
package executor

import (
	ast "go/ast"
	token "go/token"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockfiler is a mock of filer interface.
type Mockfiler struct {
	ctrl     *gomock.Controller
	recorder *MockfilerMockRecorder
}

// MockfilerMockRecorder is the mock recorder for Mockfiler.
type MockfilerMockRecorder struct {
	mock *Mockfiler
}

// NewMockfiler creates a new mock instance.
func NewMockfiler(ctrl *gomock.Controller) *Mockfiler {
	mock := &Mockfiler{ctrl: ctrl}
	mock.recorder = &MockfilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockfiler) EXPECT() *MockfilerMockRecorder {
	return m.recorder
}

// createTmpFile mocks base method.
func (m *Mockfiler) createTmpFile() (*os.File, string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createTmpFile")
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(func())
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// createTmpFile indicates an expected call of createTmpFile.
func (mr *MockfilerMockRecorder) createTmpFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createTmpFile", reflect.TypeOf((*Mockfiler)(nil).createTmpFile))
}

// flush mocks base method.
func (m *Mockfiler) flush(ast *ast.File, targetFile *os.File, fset *token.FileSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "flush", ast, targetFile, fset)
	ret0, _ := ret[0].(error)
	return ret0
}

// flush indicates an expected call of flush.
func (mr *MockfilerMockRecorder) flush(ast, targetFile, fset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "flush", reflect.TypeOf((*Mockfiler)(nil).flush), ast, targetFile, fset)
}
