// Code generated by MockGen. DO NOT EDIT.
// Source: ./fset_provider.go
//
// Generated by this command:
//
//	mockgen -package=executor -source=./fset_provider.go -destination=./fset_provider_mock.go
//
// Package executor is a generated GoMock package.
package executor

import (
	token "go/token"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockfsetProvider is a mock of fsetProvider interface.
type MockfsetProvider struct {
	ctrl     *gomock.Controller
	recorder *MockfsetProviderMockRecorder
}

// MockfsetProviderMockRecorder is the mock recorder for MockfsetProvider.
type MockfsetProviderMockRecorder struct {
	mock *MockfsetProvider
}

// NewMockfsetProvider creates a new mock instance.
func NewMockfsetProvider(ctrl *gomock.Controller) *MockfsetProvider {
	mock := &MockfsetProvider{ctrl: ctrl}
	mock.recorder = &MockfsetProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfsetProvider) EXPECT() *MockfsetProviderMockRecorder {
	return m.recorder
}

// fset mocks base method.
func (m *MockfsetProvider) fset() *token.FileSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "fset")
	ret0, _ := ret[0].(*token.FileSet)
	return ret0
}

// fset indicates an expected call of fset.
func (mr *MockfsetProviderMockRecorder) fset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "fset", reflect.TypeOf((*MockfsetProvider)(nil).fset))
}
