// Code generated by MockGen. DO NOT EDIT.
// Source: ./import_path_resolver.go
//
// Generated by this command:
//
//	mockgen -package=executor -source=./import_path_resolver.go -destination=./import_path_resolver_mock.go
//
// Package executor is a generated GoMock package.
package executor

import (
	reflect "reflect"

	types "github.com/kakkky/gonsole/types"
	gomock "go.uber.org/mock/gomock"
)

// MockimportPathResolver is a mock of importPathResolver interface.
type MockimportPathResolver struct {
	ctrl     *gomock.Controller
	recorder *MockimportPathResolverMockRecorder
}

// MockimportPathResolverMockRecorder is the mock recorder for MockimportPathResolver.
type MockimportPathResolverMockRecorder struct {
	mock *MockimportPathResolver
}

// NewMockimportPathResolver creates a new mock instance.
func NewMockimportPathResolver(ctrl *gomock.Controller) *MockimportPathResolver {
	mock := &MockimportPathResolver{ctrl: ctrl}
	mock.recorder = &MockimportPathResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockimportPathResolver) EXPECT() *MockimportPathResolverMockRecorder {
	return m.recorder
}

// resolve mocks base method.
func (m *MockimportPathResolver) resolve(pkgName types.PkgName) (types.ImportPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "resolve", pkgName)
	ret0, _ := ret[0].(types.ImportPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// resolve indicates an expected call of resolve.
func (mr *MockimportPathResolverMockRecorder) resolve(pkgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "resolve", reflect.TypeOf((*MockimportPathResolver)(nil).resolve), pkgName)
}
