package main

import (
	"bytes"
	"fmt"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/kakkky/gonsole/types"
)

func main() {
	goSrcRoot := build.Default.GOROOT + "/src"
	builtGoVersion := runtime.Version()

	// 標準パッケージ名 -> import pathのマップを構築
	pkgMap := make(map[types.PkgName][]types.ImportPath)

	fset := token.NewFileSet()
	mode := parser.ParseComments | parser.AllErrors
	skipBasePaths := []string{"vendor", "internal", "testdata", "cmd", "runtime", "benchmark"}
	err := filepath.WalkDir(goSrcRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		if slices.Contains(skipBasePaths, filepath.Base(path)) {
			return filepath.SkipDir
		}
		// _test.goファイルを除外するフィルタ
		filter := func(info fs.FileInfo) bool {
			return !strings.HasSuffix(info.Name(), "_test.go")
		}
		node, err := parser.ParseDir(fset, path, filter, mode)
		if err != nil {
			return err
		}

		// 相対パスからimport pathを計算
		relPath, _ := filepath.Rel(goSrcRoot, path)
		if relPath == "." {
			return nil
		}
		importPath := types.ImportPath(filepath.ToSlash(relPath))

		for pkgName := range node {
			// _testパッケージとmainパッケージは除外
			if strings.HasSuffix(string(pkgName), "_test") || pkgName == "main" {
				continue
			}
			// 重複チェック
			found := false
			for _, existing := range pkgMap[types.PkgName(pkgName)] {
				if existing == importPath {
					found = true
					break
				}
			}
			if !found {
				pkgMap[types.PkgName(pkgName)] = append(pkgMap[types.PkgName(pkgName)], importPath)
			}
		}

		return nil
	})

	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	buf.WriteString("package executor\n\n")
	buf.WriteString("import \"github.com/kakkky/gonsole/types\"\n\n")
	buf.WriteString("var stdPkgImportPathMap = map[types.PkgName][]types.ImportPath{\n")

	for pkgName, importPaths := range pkgMap {
		buf.WriteString(fmt.Sprintf("\t%q: {", string(pkgName)))
		for i, importPath := range importPaths {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(fmt.Sprintf("types.ImportPath(`\"%s\"`)", importPath))
		}
		buf.WriteString("},\n")
	}

	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	f, err := os.Create("executor/gen_stdpkg_importpath_map.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintf(f, "// Code generated by scripts/generate_stdpkg_importpath_map/main.go; DO NOT EDIT.\n")
	fmt.Fprintf(f, "// Go version: %s\n\n", builtGoVersion)
	f.Write(formatted)
}
