// Code generated by MockGen. DO NOT EDIT.
// Source: ./filer.go
//
// Generated by this command:
//
//	mockgen -package=filer -source=./filer.go -destination=./filer_mock.go
//
// Package filer is a generated GoMock package.
package filer

import (
	ast "go/ast"
	token "go/token"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFiler is a mock of Filer interface.
type MockFiler struct {
	ctrl     *gomock.Controller
	recorder *MockFilerMockRecorder
}

// MockFilerMockRecorder is the mock recorder for MockFiler.
type MockFilerMockRecorder struct {
	mock *MockFiler
}

// NewMockFiler creates a new mock instance.
func NewMockFiler(ctrl *gomock.Controller) *MockFiler {
	mock := &MockFiler{ctrl: ctrl}
	mock.recorder = &MockFilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiler) EXPECT() *MockFilerMockRecorder {
	return m.recorder
}

// CreateTmpFile mocks base method.
func (m *MockFiler) CreateTmpFile() (*os.File, string, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTmpFile")
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(func())
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateTmpFile indicates an expected call of CreateTmpFile.
func (mr *MockFilerMockRecorder) CreateTmpFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTmpFile", reflect.TypeOf((*MockFiler)(nil).CreateTmpFile))
}

// Flush mocks base method.
func (m *MockFiler) Flush(ast *ast.File, targetFile *os.File, fset *token.FileSet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ast, targetFile, fset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockFilerMockRecorder) Flush(ast, targetFile, fset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockFiler)(nil).Flush), ast, targetFile, fset)
}
